@AcademicProjects.API_HostAddress = http://localhost:5113
@accessToken = paste-token-here

POST {{AcademicProjects.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Student",
  "lastName": "Example",
  "email": "student@example.com",
  "password": "Student123!"
}

###

POST {{AcademicProjects.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "student@example.com",
  "password": "Student123!"
}

###

GET {{AcademicProjects.API_HostAddress}}/api/auth/me
Authorization: Bearer {{accessToken}}

###
